### PR TITLE
Add a cron job for generating CDSA records

### PR DESCRIPTION
**Pull request by amstilp**
- Modify the cdsa_records command to accept --outdir as a keyword argument instead of as a positional argument

### CODE REVIEW

**Comment by amstilp** [comment]
@jmcarson is this ready to go? And then are there instructions anywhere for adding the updated crontab file to cron when deploying?

**Comment by jmcarson** [comment]
Yes, ready to go from my perspective.  To install run:
`sudo -u <deployment_user> crontab <crontab_file>`
I thought I added to docs, but have not yet.

**Comment by jmcarson** [comment]
I can deploy and update the docs at the same time, but probably not until Monday

**Comment by amstilp** [comment]
@jmcarson I deployed this and I think I set up the cron job - I'll let you know if I don't see it run next weekend.

**Pull request merged**
